# Model M1: CNN front-end + Transformer encoder
model_name: cnn_transformer
cnn_channels: [64, 128, 256]
cnn_kernel: 3
cnn_pool: [[2, 2], [1, 2], [1, 2]]
proj_dim: 256
transformer:
  d_model: 256
  nhead: 4
  num_layers: 2
  dim_feedforward: 512
  dropout: 0.2
attention_pool: true
num_products: 10
num_quantities: 5
